fish_app/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('trips/',include('trips.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

fish_app/trips/urls.py
from django.urls import path
from .views import TripDeleteView, TripDetailView, TopView, UserTripsView, CommentDeleteView
from . import views

urlpatterns = [
  path('index/', TopView.as_view(), name="index" ),
  path('create/', views.make_inline_formset, name='create'),
  path('search/',views.search,name='search'),
  path('<int:pk>/',TripDetailView.as_view(),name='trip_detail'),
  path('<int:pk>/update/',views.update_inline_formset, name='update'),
  path('user/<int:pk>/',UserTripsView.as_view(),name='user_trips'),
  path('<int:pk>/delete/', TripDeleteView.as_view(), name='delete'),
  path('comment/<int:pk>/', CommentDeleteView.as_view(), name="comment_delete")
]

fish_app/trips/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator

class Trip(models.Model):
    class Meta:
        db_table = 'trip'
        verbose_name = '釣行'

    def __str__(self):
        return '<' 'trip_id=' + str(self.id) + 'user=' + str(self.user) + '>'

    title = models.CharField(max_length=30, verbose_name='タイトル')
    prefecture = models.CharField(max_length=4, verbose_name='都道府県')
    content = models.CharField(max_length=1000, verbose_name='内容')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='作成日時')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)


class Result(models.Model):
    class Meta:
        db_table = 'result'
        verbose_name = '釣果'

    def __str__(self):
        return '<' 'result_id=' + str(self.id) + '>'
    
    fish_name = models.CharField(max_length=20, verbose_name='魚名',validators=[RegexValidator(r'^([ァ-ン]|ー)+$','全角カナで入力してください')])
    image = models.ImageField(upload_to='images/', verbose_name='画像(任意)', null=True, blank=True)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True, verbose_name='投稿日時')


class Comment(models.Model):
    class Meta:
        db_table = 'comment'
        verbose_name = 'コメント'

    def __str__(self):
        return '<' 'comment_id=' + str(self.id) + '>'
    
    content = models.CharField(max_length=200, verbose_name='コメント内容')
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True, verbose_name='投稿日時')
    
    

fish_app/trips/forms.py
from django import forms
from .models import  Comment, Trip
from django.core.validators import RegexValidator
from .prefectures import choice_prefectures

class TripForm(forms.ModelForm):
    prefecture = forms.ChoiceField(label='場所',choices=choice_prefectures)
    class Meta:
        model = Trip
        fields = ['title', 'content',]
        widgets = {'content': forms.Textarea(attrs={'rows':3})}


class TripFindForm(forms.Form):
    keyword_fish_name = forms.CharField(label='魚名',required=True,
                validators=[RegexValidator(r'^([ァ-ン]|ー)+$','全角カナで入力してください')],
                widget=forms.TextInput(attrs={'placeholder':'全角カナ','class':'form-control mr-3'}))
    keyword_prefecture = forms.ChoiceField(label='場所',choices=choice_prefectures,required=False,
                widget=forms.Select(attrs={'class':'form-control mr-3'}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content', 'trip', 'user']
        widgets = {'content': forms.Textarea(attrs={'rows':3,'class':'form-control col-8 m-auto'})}

fish_app/trips/views.py
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.shortcuts import render
from django.views.generic import DetailView, ListView, DeleteView
from django.views import View
from django.views.generic.edit import FormMixin
from .forms import CommentForm, TripForm, TripFindForm
from .models import Comment, Trip, Result
from django.shortcuts import redirect
from . import graph
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse


class TopView(ListView):
    template_name = 'trips/index.html'
    model = Trip
    paginate_by = 6

    def get_queryset(self):
        return Trip.objects.all().select_related('user').prefetch_related('result_set').order_by('-created_at')


@login_required
def make_inline_formset(request):

    ResultFormSet = forms.inlineformset_factory(
        parent_model=Trip,
        model=Result,
        fields=('fish_name','image'),
        extra=1,
        can_delete=False,
        widgets={'image':forms.FileInput(attrs={'class':'form-control-file'}),
                 'fish_name':forms.TextInput(attrs={'placeholder':'全角カナ'})
        }
    )
    if request.method == 'POST':
        title = request.POST['title']
        prefecture = request.POST['prefecture']
        content = request.POST['content']
        user = request.user
        trip = Trip(title=title, prefecture=prefecture, content=content, user=user)
 
        formset = ResultFormSet(
            data=request.POST,
            files=request.FILES,
            instance=trip,
            queryset=Result.objects.none(),
        )
        if formset.is_valid():
            trip.save()
            formset.save()
            return redirect(to='/trips/index')
        else:
            return render(request, 'trips/create.html',{'formset':formset,'trip_form':TripForm(request.POST)})
    else:
        formset = ResultFormSet(
            queryset=Result.objects.none(),
        )
    return render(request, 'trips/create.html',{'formset':formset,'trip_form':TripForm()})


@login_required
def update_inline_formset(request,pk):
    if not request.user.id == Trip.objects.get(id=pk).user_id:
        return redirect(to='/trips/index')
    
    ResultFormSet = forms.inlineformset_factory(
        parent_model=Trip,
        model=Result,
        fields=('fish_name','image'),
        extra=1,
        can_delete=False,
        widgets={'image':forms.FileInput(attrs={'class':'form-control-file'}),
                 'fish_name':forms.TextInput(attrs={'placeholder':'全角カナ'})
        }
    )
    if request.method == 'POST':
        trip = Trip.objects.get(id=pk)
        trip.title = request.POST['title']
        trip.prefecture = request.POST['prefecture']
        trip.content = request.POST['content']
        trip.user = request.user

        formset = ResultFormSet(
            data=request.POST,
            files=request.FILES,
            instance=trip,
            queryset=Result.objects.none(),
        )

        if formset.is_valid():
            trip.save()
            formset.save()
            result_ids = request.POST.getlist('delete')
            Result.objects.filter(pk__in=result_ids).delete()
            return redirect(to='trip_detail', pk=trip.id)
        else:
            return render(request, 'trips/update.html',{'formset':formset,'trip_form':TripForm(request.POST)})
    else:
        formset = ResultFormSet(
            instance=Trip.objects.get(id=pk),
            queryset=Result.objects.none(),
        )
    results = Result.objects.filter(trip__id=pk)
    return render(request, 'trips/update.html',{'results':results,'pk':pk,'formset':formset,'trip_form':TripForm(instance=Trip.objects.get(id=pk),initial={'prefecture':Trip.objects.get(id=pk).prefecture})})









def search(request):
    if (request.method == 'POST'):
        form = TripFindForm(request.POST)
        keyword_fish_name = request.POST['keyword_fish_name']
        keyword_prefecture = request.POST['keyword_prefecture']
        if keyword_prefecture == '':
            results = Result.objects.filter(fish_name=keyword_fish_name).values(
                'fish_name','image','trip_id','created_at','trip__title','trip__prefecture','trip__user__username','trip__user__id')
            for result in results:
                result['image_url'] = f"{settings.MEDIA_IMAGE_URL}/{result['image']}"
        else:
            results = Result.objects.filter(fish_name=keyword_fish_name).filter(trip__prefecture=keyword_prefecture).values(
                'fish_name','image','trip_id','created_at','trip__title','trip__prefecture','trip__user__username','trip__user__id')
            for result in results:
                result['image_url'] = f"{settings.MEDIA_IMAGE_URL}/{result['image']}"
        result_list = list(results.values_list('created_at__month',flat=True))
        x = list(range(1,13))
        y = []
        for i in range(1,13):
            y.append(result_list.count(i))
        chart = graph.plot_graph(x,y)

        return render(request, 'trips/trip_search.html', {'form':form, 'results':results, 'chart':chart})
    else:
        form =TripFindForm()
        return render(request, 'trips/trip_search.html', {'form':form})


class TripDetailView(FormMixin, DetailView):
    model = Trip
    form_class = CommentForm

    def get_success_url(self):
        return reverse('trip_detail', kwargs={'pk': self.object.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm(initial={'trip': self.object})
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.id:
            return redirect(to='login')
        copied = request.POST.copy()
        copied['user'] = request.user.id
        self.object = self.get_object()
        form = CommentForm(copied)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)




class UserTripsView(ListView):
    model = Trip
    template_name = 'trips/user_trips.html'
    paginate_by = 6
    
    def get_queryset(self,**kwargs):
        return Trip.objects.filter(user_id=self.kwargs['pk']).select_related('user').prefetch_related('result_set').order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['account'] = get_user_model().objects.get(id=self.kwargs['pk'])
        return context


class TripDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Trip
    success_url = '/trips/index'

    def test_func(self):
        user = self.request.user
        return user == Trip.objects.get(id=self.kwargs['pk']).user


class CommentDeleteView(LoginRequiredMixin,UserPassesTestMixin,View):
    model = Comment
    
    def test_func(self):
        user = self.request.user
        return user == Comment.objects.get(id=self.kwargs['pk']).user

    def post(self,request,*args,**kwargs):
        comment = Comment.objects.get(id=self.kwargs['pk'])
        trip = comment.trip
        comment.delete()
        return redirect(to='trip_detail', pk=trip.id)

fish_app/templates/trips/create.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}新規投稿{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/
    bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body class="bg-light">
  <header>
    <nav class="navbar navbar-expand navbar-light bg-primary">
      <h3 class="text-white pl-5 pr-3">FishApp</h1>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link text-light" href="{% url 'index' %}">トップ </a>
          <a class="nav-item nav-link text-light" href="{% url 'search' %}">投稿検索</a>
          {% if not user.is_authenticated %}
          <a class="nav-item nav-link text-light" href="{% url 'login' %}">ログイン</a>
          <a class="nav-item nav-link text-light" href="{% url 'signup' %}">ユーザー登録</a>
          {% endif %}
          {% if user.is_authenticated %}
          <a class="nav-item nav-link text-light text-right" href="{% url 'create' %}">新規投稿</a>
          <a class="nav-item nav-link text-light text-right" href="{% url 'user_trips' user.id %}">投稿履歴</a>
          <a class="nav-item nav-link text-light text-right" href="{% url 'follow_list' user.id %}">フォローリスト</a>
          <a class="nav-item nav-link text-light text-right" href="{% url 'logout' %}">ログアウト</a>
          <a class="nav-item nav-link text-light border" href="{% url 'user_trips' user.id %}">{{user.username}} でログイン中</a>
          {% endif %}
        </div>
      </div>
    </nav>
  </header>

  <div class="container bg-white mb-3 pb-3">
    <h3 class="text-center py-3 my-5">新規投稿</h1>
    <div class="form-wrapper d-grid col-6 mx-auto gap-2 ">
      <form id="form-container" action="{% url 'create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="tripform">
          {% bootstrap_form trip_form %}
        </div>
        <div class="boundery border-bottom border-top text-center mb-2">釣果</div>
          {{ formset.management_form }}
          {% for form in formset %}
          <div class="result-form border p-3 mb-3 border-primary">
          {% bootstrap_form form %}
          {% endfor %}
          </div>
          <button type="button" id="add-form" class="btn btn-primary mt-2">Add</button>
          <button type="button" id="delete-form" class="btn btn-danger mt-2">Delete</button>
        <input type="submit" class="btn btn-block btn-success mt-3 mb-3">
      </form>
    </div>
  </div>


  <script>
    let resultForm = document.querySelectorAll(".result-form")
    let container = document.querySelector("#form-container")
    let addButton = document.querySelector("#add-form")
    let totalForms = document.querySelector("#id_result_set-TOTAL_FORMS")
    let deleteButton = document.querySelector("#delete-form")

    let formNum = resultForm.length-1
    addButton.addEventListener('click',addForm)
    deleteButton.addEventListener('click',deleteForm)
    console.log('hello')
    function addForm(e){
      e.preventDefault()
      console.log('hello')
      let newForm = resultForm[0].cloneNode(true)
      let formRegex = RegExp(`set-(\\d){1}-`,'g')

      formNum++
      newForm.innerHTML = newForm.innerHTML.replace(formRegex,`set-${formNum}-`)
      container.insertBefore(newForm,addButton)

      totalForms.setAttribute('value',`${formNum+1}`)
    }

    function deleteForm(e){
      e.preventDefault()
      let resultForm = document.querySelectorAll(".result-form")
      let formNum = resultForm.length-1
      let newestForm = resultForm[formNum]
      newestForm.remove()
      totalForms.setAttribute('value',`${formNum+1}`)
    } 
  </script>
</body>
</html>

fish_app/templates/trips/index.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% block title %}トップ{% endblock %}

{% block content %}
<div class="container bg-white mb-3">
<div class="row row-col-2 mt-5">
  {% for trip in page_obj %}
  <div class="trip-container col-6 border p-3">
    <div class="trip-title"><a href="/trips/{{trip.id}}" class="text-body h5">{{trip.title}}</a></div>
    <div class="d-flex mt-2">
      <div class="username">投稿日{{trip.created_at.date}}({{trip.prefecture}})</div>
      <div class="username ml-auto">投稿者：<a href="{% url 'user_trips' trip.user_id %}" class="text-body">{{trip.user.username}}</a></div>
    </div>
    <div class="fish-result my-2">釣果：
      {% for result in trip.result_set.all %}
       {{result.fish_name}}
      {% endfor %}
    </div>
    <div class="content-container my-2">
      {{trip.content | truncatechars:65}}
    </div>
    <div class="image-container">
      {% if trip.result_set.first.image %}
      <a href="{{trip.result_set.first.image.url}}"><img src="{{trip.result_set.first.image.url}}" alt="" width=80% height=auto></a>
      {% endif %}
    </div>
  </div>
  {% endfor %}
</div>





<nav aria-label="Page navigation" class="pb-3">

  <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28 mt-5">
      <!-- 前へ の部分 -->
      {% if page_obj.has_previous %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                  <span aria-hidden="true">&laquo;</span>
              </a>
          </li>
      {% endif %}

      <!-- 数字の部分 -->
      {% for num in page_obj.paginator.page_range %}
          {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

              {% if page_obj.number == num %}
                  <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
              {% else %}
                  <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
              {% endif %}
          {% endif %}
      {% endfor %}

      <!-- 次へ の部分 -->
      {% if page_obj.has_next %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                  <span aria-hidden="true">&raquo;</span>
              </a>
          </li>
      {% endif %}
  </ul>
</nav>
</div>
{% endblock %}

fish_app/templates/trips/trip_confirm_delete.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% block title %}投稿削除確認 {% endblock %}

{% block content %}
<h1>DeleteView削除確認画面</h1>
<form method="post">
    {% csrf_token %}
    <p>{{ trip.title }}を削除しますか？</p>
    <input type="submit" value="削除する">
</form>
{% endblock %}

fish_app/templates/trips/trip_detail.html
{% extends 'layout.html' %}
{% block title %}投稿詳細{% endblock %}

{% block content %}
<div class="container bg-white">
  <div class="trip-container col-12 mx-auto gap-2 d-grid py-3 my-5">
    <h2 class="text-center mt-3">{{trip.title}}</h2>
    <div class="username text-right">投稿日：{{trip.created_at.date}}</div>
    <div class="username text-right">投稿者：<a href="{% url 'user_trips' trip.user_id %}" class="text-body">{{trip.user.username}}</a></div>
    <div class="content-container d-flex mr-5">
      <div class="content-name m-2 col-1">
        内容
      </div>
      <div class="content mt-2 ml-3 mr-3 mb-2 col-11">
        {{trip.content | linebreaksbr}}
      </div>
    </div>

    <div class="content-container d-flex">
      <div class="content-name m-2 col-1">
        場所
      </div>
      <div class="content mt-2 ml-3 mb-2 col-11">
        {{trip.prefecture }}
      </div>
    </div>
    
    <div class="fish-container d-flex">
      <div class="fish-names m-2 col-1">釣果</div>
      <div class="fish-list mt-2 ml-3 mb-2 col-11">
        <div class="fish-name mb-3">
          {% for result in trip.result_set.all %}
          {{result.fish_name}}  
          {% endfor %}
        </div>
        <div class="fish-image">
          {% for result in trip.result_set.all %}
          {% if result.image %}
          <a href="{{result.image.url}}"><img src="{{result.image.url}}" width=30% height="300" class="mr-2"></a>
          {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
    {% if user.is_authenticated and user.id == trip.user.id %}
    <div class="text-right">
      <a href="{% url 'update' trip.id %}"><button class="btn btn-success btn-sm">編集</button></a>
      <a href="{% url 'delete' trip.id %}"><button class="btn btn-danger btn-sm">削除</button></a>
    </div>

    {% endif %}
  </div>
</div>

<div class="container bg-white mb-3 pb-3">
    <div class="comment-container container col-8 border-bottom">
      <p class="pt-3">コメント</p>
      {% for comment in trip.comment_set.all %}
      <div class="comment border-top">
        <div class="comment-header d-flex">
          <a href="{% url 'user_trips' comment.user.id %}" class="text-body">{{comment.user.username}}</a>
          <p class="ml-auto">{{comment.created_at.date}}</p>
        </div>
        <div class="comment-body">
          {{comment.content | linebreaksbr}}
        </div>
        {% if user.is_authenticated and user == comment.user %}
        <form action="{% url 'comment_delete' comment.id %}" method="post" class="text-right">
          {% csrf_token %}
          <input type="submit" value="削除" class="btn btn-danger btn-sm mb-1">
        </form>
        {% endif %}
      </div>
      {% endfor %}
    </div>
    {% if user.is_authenticated %}
    <form method="post" action="{% url 'trip_detail' trip.pk %}" class=" p-3">
      {% csrf_token %}
      {{form.content }}
      {{form.user.as_hidden}}
      {{form.trip.as_hidden}}
      <input type="submit" value="送信" class="btn btn-primary btn-block col-8 mt-3 mx-auto">
    </form>
    {% endif %}
</div>


{% endblock %}

fish_app/templates/trips/trip_search.html
{% extends 'layout.html' %}
{% block title %}投稿検索{% endblock %}
{% block content %}
{% load bootstrap4 %}
<div class="container bg-white mb-3">
<h3 class="my-5 text-center py-3">検索フォーム</h3>
  <div class="form-wrapper form-group d-flex border-bottom pb-3">
    <form action="{% url 'search' %}" method="post" class="form-inline mr-4">
      {% csrf_token %}
      {{form}}
      <input type="submit" class="btn btn-primary">
    </form>
    {% if results %}
    <img src="data:image/png;base64,{{ chart | safe }}" class="col-6 ">
    {% endif %}
  </div>


<div class="row row-col-3 mt-5">
  {% for result in results %}
  <div class="trip-container col-4 border p-3">
    <div class="trip-title my-2">
      <a href="{% url 'trip_detail' result.trip_id %}" class="text-body h5">{{result.trip__title}}</a>
    </div>
    <div class="d-flex mb-2">
      <div class="username">投稿日{{result.created_at.date}}{{result.trip__created_at.date}}({{result.trip__prefecture}})</div>
      <div class="username ml-auto">投稿者：<a href="{% url 'user_trips' result.trip__user__id %}" class="text-body">{{result.trip__user__username}}</a></div>
    </div>
    <div class="fish-image">
      <a href="{{result.image_url}}"><img src="{{result.image_url}}" width=100% height="auto" alt="" class="d-block mx-auto"></a>
    </div>
  </div>
  {% endfor %}
</div>

</div>
{% endblock %}

fish_app/templates/trips/user_trips.html
{% extends 'layout.html' %}
{% load bootstrap4 %}
{% block title %}ユーザー履歴{% endblock %}
{% block content %}
<div class="container bg-white mb-3">
  <h3 class="text-center mt-5 pt-3">{{account.username}}さんの投稿履歴</h1>
  <div class="wrapper d-flex">
    <div class="user-info col-4 mt-5 mr-3">
    <p>ユーザー名：{{account.username}}</p>
    <p>投稿数：{{ account.trip_set.all.count }}</p>
    <p><a class="text-info" href="{% url 'follow_list' account.id %}">>>フォローリスト</a></p>
    <p>自己紹介</p>
    <div class="intro-content mb-3 border-top border-bottom py-2">
      {{account.introduce| linebreaksbr}}
    </div>
    {% if user.is_authenticated and user.id == account.id %}
    <a href="{% url 'user_update' account.id %}"><button class="btn btn-success btn-sm">編集</button></a>
    {% endif %}
  </div>
  
  <div class="index col-8">
    <div class="row row-col-2 mt-5">
      {% for trip in page_obj %}
      <div class="trip-container col-6 border p-3">
        <div class="trip-title"><a href="/trips/{{trip.id}}" class="text-body h5">{{trip.title}}</a></div>
        <div class="d-flex">
          <div class="username">投稿日{{trip.created_at.date}}({{trip.prefecture}})</div>
          <div class="username ml-auto">投稿者：{{trip.user.username}}</div>
        </div>
        <div class="fish-result my-2">釣果：
          {% for fish in trip.result_set.all %}
          {{fish.fish_name}}
          {% endfor %}
        </div>
        <div class="content-container my-2">
          {{trip.content | truncatechars:65}}
        </div>
        <div class="image-container">
          {% if trip.result_set.first.image %}
          <a href="{{trip.result_set.first.image.url}}"><img src="{{trip.result_set.first.image.url}}" alt="" width=100% height=auto></a>
          {% endif %}
        </div>
      </div>
      {% endfor %}
    </div>

    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28 mt-5">
          <!-- 前へ の部分 -->
          {% if page_obj.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                      <span aria-hidden="true">&laquo;</span>
                  </a>
              </li>
          {% endif %}

          <!-- 数字の部分 -->
          {% for num in page_obj.paginator.page_range %}
              {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                  {% if page_obj.number == num %}
                      <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                  {% else %}
                      <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                  {% endif %}
              {% endif %}
          {% endfor %}

          <!-- 次へ の部分 -->
          {% if page_obj.has_next %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                      <span aria-hidden="true">&raquo;</span>
                  </a>
              </li>
          {% endif %}
      </ul>

    </nav>
  </div>
</div>
</div>
{% endblock %}